services:
  - type: web
    name: print-calculator
    runtime: static
    buildCommand: echo "no build needed"
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
